-- ============================================================================
-- PROPOSED -- NOT APPLIED -- DO NOT RUN until Sentinel has pre-flighted the plan and Leo has approved running it.
-- live_rehearsal_rolled_back.sql  (project rnrzjlfpwxzomupnxikt)   cleanup trigger for orphaned Trello Vault secrets
--
-- WHAT IT IS: the full 20261009230000_trello_vault_cleanup_on_profile_delete.sql body followed by end-to-end checks, all
-- inside ONE transaction that ends in a deliberate error, so NOTHING COMMITS. Expected outcome: ERROR starting
-- "REHEARSAL_ROLLBACK (deliberate, nothing committed)" followed by one line per check, all "ok" (or "--" for a documented
-- skip). Any line starting "REHEARSAL_FAILED" means a check failed (that also changes nothing).
--
-- WHAT IT TOUCHES: it never reads or changes Leo's Trello credential. It creates two THROWAWAY users (auth.users rows with
-- random uuids and fake credential-shaped values), stores fake credentials for one, deletes both users and checks the trigger
-- removed exactly that user's secrets. All of it is rolled back. The migration's one-time sweep also runs inside the
-- transaction; the number of orphans it would remove is reported (a count, no names or values).
-- It takes brief locks on public.profiles and auth.users. NO CREDENTIAL VALUE IS PRINTED.
--
-- LIMIT: from the SQL editor (role postgres, not a superuser) this script cannot become supabase_auth_admin, the role Supabase
-- Auth deletes users with, so the Admin-API path is NOT exercised here (the local replica tests emulate it with SET SESSION
-- AUTHORIZATION). After any real apply, delete a throwaway test user through the Admin API as the first live check (REPORT.md).
-- Generated by test/build_rehearsal.mjs: the block between the BODY markers is the migration, byte for byte.
-- ============================================================================
begin;

create temp table _rh_out (n serial, line text) on commit drop;
create temp table _rh_before on commit drop as
  select (select count(*) from vault.secrets) as secrets,
         (select count(*) from public.profiles) as profiles,
         (select count(*) from public.profiles where trello_api_key_id is not null) as connected;

-- >>> MIGRATION BODY BEGIN

-- ---- 1. pre-flight --------------------------------------------------------
do $$
declare
  missing text;
begin
  select string_agg(c, ', ') into missing
    from unnest(array['trello_api_key_id', 'trello_token_id']) as c
   where not exists (select 1 from pg_attribute a
                      where a.attrelid = 'public.profiles'::regclass and a.attname = c and a.attnum > 0 and not a.attisdropped);
  if missing is not null then
    raise exception 'public.profiles is missing column(s): % (is the Trello Vault migration applied?)', missing;
  end if;
  if to_regprocedure('public.trello_clear_credentials(uuid)') is null then
    raise exception 'public.trello_clear_credentials(uuid) not found: the Trello Vault migration is not in place';
  end if;
  if to_regclass('vault.secrets') is null then
    raise exception 'vault.secrets not found';
  end if;
  if not has_schema_privilege(current_user, 'vault', 'USAGE')
     or not has_table_privilege(current_user, 'vault.secrets', 'SELECT')
     or not has_table_privilege(current_user, 'vault.secrets', 'DELETE') then
    raise exception 'role % lacks USAGE on vault or SELECT/DELETE on vault.secrets: missing Vault privileges', current_user;
  end if;
  if not pg_has_role(current_user, (select c.relowner from pg_class c where c.oid = 'public.profiles'::regclass), 'USAGE') then
    raise exception 'role % is not the owner of public.profiles, so it cannot create a trigger on it', current_user;
  end if;
end $$;

-- ---- 2. trigger function and trigger --------------------------------------
create or replace function public.trello_cleanup_vault_on_profile_delete()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  ids uuid[] := array_remove(array[old.trello_api_key_id, old.trello_token_id], null);
begin
  -- Vault 0.3.1 has no delete_secret(); a direct delete is the supported way. The two named secrets are included so a
  -- profile whose id column was nulled by hand still leaves nothing behind.
  delete from vault.secrets
   where id = any (ids)
      or name in ('trello_api_key:' || old.id::text, 'trello_token:' || old.id::text);
  if exists (select 1 from vault.secrets
              where id = any (ids)
                 or name in ('trello_api_key:' || old.id::text, 'trello_token:' || old.id::text)) then
    raise exception 'trello_cleanup_vault_on_profile_delete: Vault secret(s) of profile % still present after delete', old.id
      using errcode = 'XX000';
  end if;
  return old;
end
$fn$;

-- A trigger function is never called directly. Nobody but the owner needs EXECUTE; the default privileges would otherwise
-- hand it to anon/authenticated/service_role (it cannot be invoked as a plain function anyway; this is belt and braces).
revoke all on function public.trello_cleanup_vault_on_profile_delete() from public, anon, authenticated, service_role;

create or replace trigger trello_cleanup_vault_on_profile_delete
  after delete on public.profiles
  for each row
  when (old.trello_api_key_id is not null or old.trello_token_id is not null)
  execute function public.trello_cleanup_vault_on_profile_delete();

-- ---- 3. one-time sweep of secrets already orphaned ------------------------------
do $$
declare
  swept int;
begin
  delete from vault.secrets s
   where s.name ~ '^trello_(api_key|token):[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
     and not exists (select 1 from public.profiles p
                      where p.trello_api_key_id = s.id or p.trello_token_id = s.id
                         or p.id::text = substr(s.name, position(':' in s.name) + 1));
  get diagnostics swept = row_count;
  raise notice 'trello_vault_cleanup: swept % orphaned secret(s)', swept;
end $$;

-- ---- 4. post-flight --------------------------------------------------------------
do $$
declare
  who text;
begin
  if not exists (select 1
                   from pg_trigger t
                  where t.tgrelid = 'public.profiles'::regclass and t.tgname = 'trello_cleanup_vault_on_profile_delete'
                    and not t.tgisinternal
                    and t.tgenabled = 'O'                       -- enabled for ordinary sessions
                    and (t.tgtype & 1) = 1                      -- row-level
                    and (t.tgtype & 2) = 0                      -- not BEFORE
                    and (t.tgtype & 4) = 0 and (t.tgtype & 16) = 0 and (t.tgtype & 8) = 8 and (t.tgtype & 32) = 0   -- DELETE only
                    and t.tgfoid = 'public.trello_cleanup_vault_on_profile_delete()'::regprocedure) then
    raise exception 'the cleanup trigger is missing, disabled, or not AFTER DELETE FOR EACH ROW';
  end if;
  if not coalesce((select p.prosecdef and exists (select 1 from unnest(p.proconfig) c where c in ('search_path=""', 'search_path='))
                     from pg_proc p where p.oid = 'public.trello_cleanup_vault_on_profile_delete()'::regprocedure), false) then
    raise exception 'the trigger function is not SECURITY DEFINER with an empty search_path';
  end if;
  foreach who in array array['anon', 'authenticated', 'service_role'] loop
    if has_function_privilege(who, 'public.trello_cleanup_vault_on_profile_delete()'::regprocedure, 'EXECUTE') then
      raise exception '% can EXECUTE the trigger function', who;
    end if;
  end loop;
  if exists (select 1 from pg_proc p, aclexplode(p.proacl) x
              where p.oid = 'public.trello_cleanup_vault_on_profile_delete()'::regprocedure
                and x.privilege_type = 'EXECUTE' and x.grantee = 0) then
    raise exception 'PUBLIC can EXECUTE the trigger function (pg_proc.proacl)';
  end if;
  if exists (select 1 from pg_proc p, aclexplode(p.proacl) x
              join pg_roles r on r.oid = x.grantee
              where p.oid = 'public.trello_cleanup_vault_on_profile_delete()'::regprocedure
                and x.privilege_type = 'EXECUTE' and x.grantee <> p.proowner and r.rolname not in ('postgres', 'supabase_admin')) then
    raise exception 'an unexpected role can EXECUTE the trigger function (pg_proc.proacl)';
  end if;
  if exists (select 1 from vault.secrets s
              where s.name ~ '^trello_(api_key|token):[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
                and not exists (select 1 from public.profiles p
                                 where p.trello_api_key_id = s.id or p.trello_token_id = s.id
                                    or p.id::text = substr(s.name, position(':' in s.name) + 1))) then
    raise exception 'an orphaned Trello Vault secret remains';
  end if;
  if exists (select 1 from public.profiles p
              where (p.trello_api_key_id is not null and not exists (select 1 from vault.secrets s where s.id = p.trello_api_key_id))
                 or (p.trello_token_id is not null and not exists (select 1 from vault.secrets s where s.id = p.trello_token_id))) then
    raise exception 'a profile points at a Vault secret that does not exist (the sweep must never remove a referenced secret)';
  end if;
  raise notice 'trello_vault_cleanup: post-flight passed';
end $$;

-- <<< MIGRATION BODY END

-- ---- rehearsal checks (everything below runs inside the same transaction) ----------------------------------------
do $$
declare
  b record;
  u1 uuid := gen_random_uuid();
  u2 uuid := gen_random_uuid();
  k1 uuid;
  t1 uuid;
  n int;
begin
  select * into b from _rh_before;
  -- the existing real profiles are untouched by the trigger and the sweep
  if (select count(*) from public.profiles where trello_api_key_id is not null) <> b.connected
     or (select count(*) from public.profiles) <> b.profiles then
    raise exception 'REHEARSAL_FAILED: the migration changed the number of profiles or connected profiles';
  end if;
  insert into _rh_out(line) values (format('ok  profiles: %s (%s connected) unchanged; vault.secrets: %s before, %s after the sweep',
    b.profiles, b.connected, b.secrets, (select count(*) from vault.secrets)));

  insert into _rh_out(line) values (format('ok  supabase_auth_admin exists: %s; may DELETE auth.users: %s (the real Admin-API path is not exercised by this script)',
    exists (select 1 from pg_roles where rolname = 'supabase_auth_admin'),
    coalesce(has_table_privilege('supabase_auth_admin', 'auth.users', 'DELETE'), false)));

  -- throwaway users; the signup trigger creates their profiles on the real database, make sure either way
  begin
    insert into auth.users (id, email) values (u1, 'rehearsal-' || u1 || '@example.invalid'), (u2, 'rehearsal-' || u2 || '@example.invalid');
  exception when others then
    insert into _rh_out(line) values (format('--  could not create a throwaway auth.users row (SQLSTATE %s): trigger behaviour test skipped', sqlstate));
    return;
  end;
  insert into public.profiles (id, email) values (u1, 'rehearsal-' || u1 || '@example.invalid'), (u2, 'rehearsal-' || u2 || '@example.invalid')
    on conflict (id) do nothing;

  -- user 1 gets (fake) credentials through the real function, as service_role
  set local role service_role;
  if not public.trello_store_credentials(u1, 'REHEARSALKEY' || replace(u1::text, '-', ''), 'REHEARSALTOKEN' || replace(u1::text, '-', '')) then
    reset role;
    raise exception 'REHEARSAL_FAILED: could not store the throwaway credential';
  end if;
  reset role;
  select trello_api_key_id, trello_token_id into k1, t1 from public.profiles where id = u1;
  if k1 is null or t1 is null or (select count(*) from vault.secrets where id in (k1, t1)) <> 2 then
    raise exception 'REHEARSAL_FAILED: throwaway user did not end up with two Vault secrets';
  end if;
  insert into _rh_out(line) values ('ok  throwaway user connected: two Vault secrets exist');

  -- delete both users the way a direct SQL delete would (cascades to profiles, which fires the trigger)
  delete from auth.users where id = u2;
  if exists (select 1 from public.profiles where id = u2) then
    raise exception 'REHEARSAL_FAILED: deleting a user without Trello left the profile behind';
  end if;
  insert into _rh_out(line) values ('ok  deleting a user with no Trello connection: no error, profile cascaded away');

  delete from auth.users where id = u1;
  select count(*) into n from vault.secrets where id in (k1, t1) or name in ('trello_api_key:' || u1, 'trello_token:' || u1);
  if n <> 0 or exists (select 1 from public.profiles where id = u1) then
    raise exception 'REHEARSAL_FAILED: after deleting the connected user, % of its Vault secrets remain (or the profile remains)', n;
  end if;
  insert into _rh_out(line) values ('ok  deleting a Trello-connected user: its two Vault secrets are gone, no error');

  if (select count(*) from public.profiles) <> b.profiles then
    raise exception 'REHEARSAL_FAILED: profile count differs after the throwaway deletes';
  end if;
  insert into _rh_out(line) values (format('ok  profiles back to %s after the throwaway deletes; trigger function executable by anon/authenticated/service_role: %s/%s/%s',
    b.profiles,
    has_function_privilege('anon', 'public.trello_cleanup_vault_on_profile_delete()'::regprocedure, 'EXECUTE'),
    has_function_privilege('authenticated', 'public.trello_cleanup_vault_on_profile_delete()'::regprocedure, 'EXECUTE'),
    has_function_privilege('service_role', 'public.trello_cleanup_vault_on_profile_delete()'::regprocedure, 'EXECUTE')));
end $$;

-- ---- the deliberate error: report and abort --------------------------------------------------------------------------
do $$
begin
  raise exception 'REHEARSAL_ROLLBACK (deliberate, nothing committed):%', E'\n' || (select string_agg(line, E'\n' order by n) from _rh_out);
end $$;

rollback;   -- only reached by a client that keeps going after the error
