// Regenerates ../live_rehearsal_rolled_back.sql from the migration, so the rehearsal always embeds the migration body verbatim.
//   node test/build_rehearsal.mjs        (the test suite also fails if the two ever differ)
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export const DIR = join(dirname(fileURLToPath(import.meta.url)), '..');
export const MIGRATION_FILE = '20261009230000_trello_vault_cleanup_on_profile_delete.sql';

export function extractBody(sql) {
  const a = sql.indexOf('-- >>> MIGRATION BODY BEGIN');
  const b = sql.indexOf('-- <<< MIGRATION BODY END');
  if (a < 0 || b < 0) throw new Error('markers not found');
  return sql.slice(sql.indexOf('\n', a) + 1, b);
}

const HEAD = `-- ============================================================================
-- PROPOSED -- NOT APPLIED -- DO NOT RUN until Sentinel has pre-flighted the plan and Leo has approved running it.
-- live_rehearsal_rolled_back.sql  (project rnrzjlfpwxzomupnxikt)   cleanup trigger for orphaned Trello Vault secrets
--
-- WHAT IT IS: the full ${MIGRATION_FILE} body followed by end-to-end checks, all
-- inside ONE transaction that ends in a deliberate error, so NOTHING COMMITS. Expected outcome: ERROR starting
-- "REHEARSAL_ROLLBACK (deliberate, nothing committed)" followed by one line per check, all "ok" (or "--" for a documented
-- skip). Any line starting "REHEARSAL_FAILED" means a check failed (that also changes nothing).
--
-- WHAT IT TOUCHES: it never reads or changes Leo's Trello credential. It creates two THROWAWAY users (auth.users rows with
-- random uuids and fake credential-shaped values), stores fake credentials for one, deletes both users and checks the trigger
-- removed exactly that user's secrets. All of it is rolled back. The migration's one-time sweep also runs inside the
-- transaction; the number of orphans it would remove is reported (a count, no names or values).
-- It takes brief locks on public.profiles and auth.users. NO CREDENTIAL VALUE IS PRINTED.
--
-- LIMIT: from the SQL editor (role postgres, not a superuser) this script cannot become supabase_auth_admin, the role Supabase
-- Auth deletes users with, so the Admin-API path is NOT exercised here (the local replica tests emulate it with SET SESSION
-- AUTHORIZATION). After any real apply, delete a throwaway test user through the Admin API as the first live check (REPORT.md).
-- Generated by test/build_rehearsal.mjs: the block between the BODY markers is the migration, byte for byte.
-- ============================================================================
begin;

create temp table _rh_out (n serial, line text) on commit drop;
create temp table _rh_before on commit drop as
  select (select count(*) from vault.secrets) as secrets,
         (select count(*) from public.profiles) as profiles,
         (select count(*) from public.profiles where trello_api_key_id is not null) as connected;

-- >>> MIGRATION BODY BEGIN
`;

const TAIL = `-- <<< MIGRATION BODY END

-- ---- rehearsal checks (everything below runs inside the same transaction) ----------------------------------------
do $$
declare
  b record;
  u1 uuid := gen_random_uuid();
  u2 uuid := gen_random_uuid();
  k1 uuid;
  t1 uuid;
  n int;
begin
  select * into b from _rh_before;
  -- the existing real profiles are untouched by the trigger and the sweep
  if (select count(*) from public.profiles where trello_api_key_id is not null) <> b.connected
     or (select count(*) from public.profiles) <> b.profiles then
    raise exception 'REHEARSAL_FAILED: the migration changed the number of profiles or connected profiles';
  end if;
  insert into _rh_out(line) values (format('ok  profiles: %s (%s connected) unchanged; vault.secrets: %s before, %s after the sweep',
    b.profiles, b.connected, b.secrets, (select count(*) from vault.secrets)));

  insert into _rh_out(line) values (format('ok  supabase_auth_admin exists: %s; may DELETE auth.users: %s (the real Admin-API path is not exercised by this script)',
    exists (select 1 from pg_roles where rolname = 'supabase_auth_admin'),
    coalesce(has_table_privilege('supabase_auth_admin', 'auth.users', 'DELETE'), false)));

  -- throwaway users; the signup trigger creates their profiles on the real database, make sure either way
  begin
    insert into auth.users (id, email) values (u1, 'rehearsal-' || u1 || '@example.invalid'), (u2, 'rehearsal-' || u2 || '@example.invalid');
  exception when others then
    insert into _rh_out(line) values (format('--  could not create a throwaway auth.users row (SQLSTATE %s): trigger behaviour test skipped', sqlstate));
    return;
  end;
  insert into public.profiles (id, email) values (u1, 'rehearsal-' || u1 || '@example.invalid'), (u2, 'rehearsal-' || u2 || '@example.invalid')
    on conflict (id) do nothing;

  -- user 1 gets (fake) credentials through the real function, as service_role
  set local role service_role;
  if not public.trello_store_credentials(u1, 'REHEARSALKEY' || replace(u1::text, '-', ''), 'REHEARSALTOKEN' || replace(u1::text, '-', '')) then
    reset role;
    raise exception 'REHEARSAL_FAILED: could not store the throwaway credential';
  end if;
  reset role;
  select trello_api_key_id, trello_token_id into k1, t1 from public.profiles where id = u1;
  if k1 is null or t1 is null or (select count(*) from vault.secrets where id in (k1, t1)) <> 2 then
    raise exception 'REHEARSAL_FAILED: throwaway user did not end up with two Vault secrets';
  end if;
  insert into _rh_out(line) values ('ok  throwaway user connected: two Vault secrets exist');

  -- delete both users the way a direct SQL delete would (cascades to profiles, which fires the trigger)
  delete from auth.users where id = u2;
  if exists (select 1 from public.profiles where id = u2) then
    raise exception 'REHEARSAL_FAILED: deleting a user without Trello left the profile behind';
  end if;
  insert into _rh_out(line) values ('ok  deleting a user with no Trello connection: no error, profile cascaded away');

  delete from auth.users where id = u1;
  select count(*) into n from vault.secrets where id in (k1, t1) or name in ('trello_api_key:' || u1, 'trello_token:' || u1);
  if n <> 0 or exists (select 1 from public.profiles where id = u1) then
    raise exception 'REHEARSAL_FAILED: after deleting the connected user, % of its Vault secrets remain (or the profile remains)', n;
  end if;
  insert into _rh_out(line) values ('ok  deleting a Trello-connected user: its two Vault secrets are gone, no error');

  if (select count(*) from public.profiles) <> b.profiles then
    raise exception 'REHEARSAL_FAILED: profile count differs after the throwaway deletes';
  end if;
  insert into _rh_out(line) values (format('ok  profiles back to %s after the throwaway deletes; trigger function executable by anon/authenticated/service_role: %s/%s/%s',
    b.profiles,
    has_function_privilege('anon', 'public.trello_cleanup_vault_on_profile_delete()'::regprocedure, 'EXECUTE'),
    has_function_privilege('authenticated', 'public.trello_cleanup_vault_on_profile_delete()'::regprocedure, 'EXECUTE'),
    has_function_privilege('service_role', 'public.trello_cleanup_vault_on_profile_delete()'::regprocedure, 'EXECUTE')));
end $$;

-- ---- the deliberate error: report and abort --------------------------------------------------------------------------
do $$
begin
  raise exception 'REHEARSAL_ROLLBACK (deliberate, nothing committed):%', E'\\n' || (select string_agg(line, E'\\n' order by n) from _rh_out);
end $$;

rollback;   -- only reached by a client that keeps going after the error
`;

if (process.argv[1] && process.argv[1].endsWith('build_rehearsal.mjs')) {
  const out = HEAD + extractBody(readFileSync(join(DIR, MIGRATION_FILE), 'utf8')) + TAIL;
  writeFileSync(join(DIR, 'live_rehearsal_rolled_back.sql'), out);
  console.log('wrote live_rehearsal_rolled_back.sql', out.length, 'chars');
}
