// Regenerates ../live_rehearsal_rolled_back.sql from the migration, so the rehearsal always embeds the migration body verbatim.
//   node test/build_rehearsal.mjs        (the test suite also fails if the two ever differ)
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { DIR } from './replica.mjs';

export function extractBody(sql) {
  const a = sql.indexOf('-- >>> MIGRATION BODY BEGIN');
  const b = sql.indexOf('-- <<< MIGRATION BODY END');
  if (a < 0 || b < 0) throw new Error('markers not found');
  return sql.slice(sql.indexOf('\n', a) + 1, b);
}

const HEAD = `-- ============================================================================
-- PROPOSED -- NOT APPLIED -- DO NOT RUN. Written by Forge, to be run later by Sentinel with Leo's explicit approval.
-- live_rehearsal_rolled_back.sql  (project rnrzjlfpwxzomupnxikt)
--
-- WHAT IT IS: the full 20261009120000_trello_credentials_to_vault.sql body followed by end-to-end checks, all inside ONE
-- transaction that ends in a deliberate error, so NOTHING COMMITS. Expected outcome: ERROR starting
-- "REHEARSAL_ROLLBACK (deliberate, nothing committed)" followed by one line per check, all "ok". Any line starting
-- "REHEARSAL_FAILED" means a check failed (that also changes nothing).
--
-- WHAT IT TOUCHES: inside the doomed transaction it moves Leo's one real Trello credential into Vault, reads it back through
-- the new functions, re-stores the identical value (exercises update_secret + read-back), clears it and checks the Vault
-- secrets are gone. Because the transaction is rolled back, the real row and its plaintext come back exactly as they were
-- (Postgres sequences/WAL may still record that the writes happened; the secrets were encrypted by Vault at write time).
-- It takes ACCESS EXCLUSIVE on public.profiles for the length of the run (SET EXPRESSION rewrites the table): seconds.
-- NO CREDENTIAL VALUE IS PRINTED: the checks compare md5() hashes held in a temp table and report only counts, booleans,
-- ACL strings and profile counts; error text never includes a value.
--
-- RUN IT as the postgres role in the SQL editor / psql (one script, one transaction). It needs Migration A applied and
-- supabase_vault 0.3.1. It cannot test PostgREST (the Edge Function path); see the report for what that leaves.
-- This file is GENERATED by test/build_rehearsal.mjs: the block between the BODY markers is the migration, byte for byte.
-- ============================================================================
begin;

-- snapshot, as hashes only, of what exists before
create temp table _rh_before on commit drop as
  select id, md5(trello_api_key) as k_md5, md5(trello_token) as t_md5, trello_board_id, trello_connected
    from public.profiles
   where coalesce(trello_api_key, '') <> '' and coalesce(trello_token, '') <> '';
create temp table _rh_out (n serial, line text) on commit drop;
create temp table _rh_acl_before on commit drop as
  select (select relacl::text from pg_class where oid = 'public.profiles'::regclass) as relacl;

-- >>> MIGRATION BODY BEGIN
`;

const TAIL = `-- <<< MIGRATION BODY END

-- ---- rehearsal checks (everything below runs inside the same transaction) ----------------------------------------
do $$
declare
  r record;
  n_before int := (select count(*) from _rh_before);
  got record;
  ok_count int := 0;
  fn regprocedure;
  who text;
  st text;
  msg text;
  v_connected boolean;
begin
  insert into _rh_out(line) values (format('ok  profiles with both plaintext values before: %s (all moved)', n_before));

  -- 1. the new functions return exactly what was there before (hash comparison only)
  for r in select * from _rh_before loop
    set local role service_role;
    select * into got from public.trello_read_credentials(r.id);
    reset role;
    if md5(got.api_key) is distinct from r.k_md5 or md5(got.token) is distinct from r.t_md5 then
      raise exception 'REHEARSAL_FAILED: trello_read_credentials does not return the original credential for a migrated profile';
    end if;
    ok_count := ok_count + 1;
  end loop;
  insert into _rh_out(line) values (format('ok  trello_read_credentials returns the original credential for %s/%s migrated profile(s) (md5 match)', ok_count, n_before));

  -- 2. trello_connected unchanged for every migrated profile, and the table-level grants did not move
  if exists (select 1 from _rh_before b join public.profiles p using (id) where p.trello_connected is distinct from b.trello_connected) then
    raise exception 'REHEARSAL_FAILED: trello_connected changed for a migrated profile';
  end if;
  if (select relacl::text from pg_class where oid = 'public.profiles'::regclass) is distinct from (select relacl from _rh_acl_before) then
    raise exception 'REHEARSAL_FAILED: pg_class.relacl of public.profiles changed';
  end if;
  insert into _rh_out(line) values ('ok  trello_connected unchanged for migrated profiles; profiles table-level ACL unchanged: '
                                    || (select relacl from _rh_acl_before));

  -- 3. per-role EXECUTE, from pg_proc.proacl and has_function_privilege (not information_schema)
  foreach fn in array array['public.trello_store_credentials(uuid,text,text)'::regprocedure,
                            'public.trello_read_credentials(uuid)'::regprocedure,
                            'public.trello_clear_credentials(uuid)'::regprocedure] loop
    insert into _rh_out(line) values (format('ok  %s  anon=%s authenticated=%s service_role=%s  proacl=%s', fn::text,
      has_function_privilege('anon', fn, 'EXECUTE'), has_function_privilege('authenticated', fn, 'EXECUTE'),
      has_function_privilege('service_role', fn, 'EXECUTE'), (select proacl::text from pg_proc where oid = fn)));
  end loop;

  -- 4. anon and authenticated are refused (privilege), and still refused by the in-function check if EXECUTE were re-granted
  foreach who in array array['anon', 'authenticated'] loop
    begin
      execute format('set local role %I', who);
      perform public.trello_read_credentials('00000000-0000-0000-0000-000000000000');
      reset role;
      raise exception 'REHEARSAL_FAILED: % could call trello_read_credentials', who;
    exception when insufficient_privilege then
      reset role;
    end;
    insert into _rh_out(line) values (format('ok  %s is refused by the EXECUTE grant (42501)', who));
    -- defense in depth: grant it back inside this doomed transaction and check the function itself says no
    execute format('grant execute on function public.trello_read_credentials(uuid) to %I', who);
    begin
      execute format('set local role %I', who);
      perform public.trello_read_credentials('00000000-0000-0000-0000-000000000000');
      reset role;
      raise exception 'REHEARSAL_FAILED: % got past the in-function caller check', who;
    exception when insufficient_privilege then
      get stacked diagnostics msg = message_text;
      reset role;
      if msg not like '%service_role only%' then
        raise exception 'REHEARSAL_FAILED: the 42501 for % did not come from the in-function check', who;
      end if;
    end;
    execute format('revoke execute on function public.trello_read_credentials(uuid) from %I', who);
    insert into _rh_out(line) values (format('ok  %s with EXECUTE re-granted is still refused by the in-function check', who));
  end loop;

  -- 5. the real credential, through all three functions (skipped when nothing was migrated)
  select * into r from _rh_before limit 1;
  if found then
    set local role service_role;
    select * into got from public.trello_read_credentials(r.id);
    if not public.trello_store_credentials(r.id, got.api_key, got.token) then
      reset role;
      raise exception 'REHEARSAL_FAILED: trello_store_credentials found no profile for a real profile id';
    end if;
    select * into got from public.trello_read_credentials(r.id);
    reset role;
    if md5(got.api_key) is distinct from r.k_md5 or md5(got.token) is distinct from r.t_md5 then
      raise exception 'REHEARSAL_FAILED: re-storing the same credential changed or lost it';
    end if;
    insert into _rh_out(line) values ('ok  re-storing the identical credential (update_secret path + read-back) leaves it unchanged');

    set local role service_role;
    if not public.trello_clear_credentials(r.id) then
      reset role;
      raise exception 'REHEARSAL_FAILED: trello_clear_credentials found no profile for a real profile id';
    end if;
    select * into got from public.trello_read_credentials(r.id);
    reset role;
    select trello_connected into v_connected from public.profiles where id = r.id;
    if got.api_key is not null or got.token is not null or v_connected
       or exists (select 1 from vault.secrets where name in ('trello_api_key:' || r.id::text, 'trello_token:' || r.id::text)) then
      raise exception 'REHEARSAL_FAILED: after trello_clear_credentials the profile still reads as connected or a Vault secret remains';
    end if;
    insert into _rh_out(line) values ('ok  trello_clear_credentials: reads back as not connected, trello_connected = false, Vault secrets deleted');
  else
    insert into _rh_out(line) values ('--  no migrated profile: the real-credential round trip was skipped');
  end if;

  -- 6. the browser roles cannot write the id columns (has_column_privilege resolves table and column grants together)
  foreach who in array array['anon', 'authenticated'] loop
    if has_column_privilege(who, 'public.profiles', 'trello_api_key_id', 'UPDATE') or has_column_privilege(who, 'public.profiles', 'trello_token_id', 'UPDATE') then
      raise exception 'REHEARSAL_FAILED: % can UPDATE a Vault id column', who;
    end if;
  end loop;
  insert into _rh_out(line) values (format('ok  anon/authenticated cannot UPDATE the id columns; authenticated can still SELECT them via the table-level grant until Migration B: %s',
    has_column_privilege('authenticated', 'public.profiles', 'trello_api_key_id', 'SELECT')));
end $$;

-- ---- the deliberate error: report and abort --------------------------------------------------------------------------
do $$
begin
  raise exception 'REHEARSAL_ROLLBACK (deliberate, nothing committed):%', E'\\n' || (select string_agg(line, E'\\n' order by n) from _rh_out);
end $$;

rollback;   -- only reached by a client that keeps going after the error
`;

const out = HEAD + extractBody(readFileSync(join(DIR, '20261009120000_trello_credentials_to_vault.sql'), 'utf8')) + TAIL;
writeFileSync(join(DIR, 'live_rehearsal_rolled_back.sql'), out);
console.log('wrote live_rehearsal_rolled_back.sql', out.length, 'chars');
